version: "3"

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: "db"
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_dev:/var/lib/mysql
    env_file:
      - ./mysql.env
    networks:
      - app-tier
